<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
   <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="4.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.12" />
  </ItemGroup>
</Project>
